CREATE SCHEMA IF NOT EXISTS data_warehouse;

CREATE TABLE IF NOT EXISTS data_warehouse.DIM_GEN (
    GEN_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NM_GEN TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS data_warehouse.DIM_PRD_COM (
    COM_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NM_PRD_COM TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS data_warehouse.DIM_CNT (
    CNT_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NM_PRD_CNT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS data_warehouse.DIM_SPK_LAN (
    LAN_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NM_SPK_LAN TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS data_warehouse.DIM_DAT (
    DAT_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    DT_FULL DATE NOT NULL,
    ANO INT,
    MES INT,
    DIA INT
);

CREATE TABLE IF NOT EXISTS data_warehouse.DIM_STA (
    STA_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NM_STA TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS data_warehouse.FCT_MOV (
    MOV_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CD_MOV_NK BIGINT NOT NULL UNIQUE,
    NM_TIT TEXT NOT NULL,
    DT_REL TIMESTAMP NOT NULL,
    NM_ORI_TIT TEXT,
    QT_RUN INT,
    VL_BDG BIGINT,
    VL_REV BIGINT,
    VL_POP REAL,
    VL_VOT_AVG REAL,
    QT_VOT_CNT INT,
    TX_OVR TEXT,
    TX_TGL TEXT,
    IN_ADL BOOLEAN,
    CD_ORI_LAN TEXT,
    DAT_SRK INTEGER REFERENCES data_warehouse.DIM_DAT(DAT_SRK),
    STA_SRK INTEGER REFERENCES data_warehouse.DIM_STA(STA_SRK)
);

CREATE TABLE IF NOT EXISTS data_warehouse.MOV_GEN (
    MOV_GEN_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    MOV_SRK INTEGER REFERENCES data_warehouse.FCT_MOV(MOV_SRK),
    GEN_SRK INTEGER REFERENCES data_warehouse.DIM_GEN(GEN_SRK)
);

CREATE TABLE IF NOT EXISTS data_warehouse.MOV_COM (
    MOV_COM_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    MOV_SRK INTEGER REFERENCES data_warehouse.FCT_MOV(MOV_SRK),
    COM_SRK INTEGER REFERENCES data_warehouse.DIM_PRD_COM(COM_SRK)
);

CREATE TABLE IF NOT EXISTS data_warehouse.MOV_CNT (
    MOV_CNT_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    MOV_SRK INTEGER REFERENCES data_warehouse.FCT_MOV(MOV_SRK),
    CNT_SRK INTEGER REFERENCES data_warehouse.DIM_CNT(CNT_SRK)
);

CREATE TABLE IF NOT EXISTS data_warehouse.MOV_LAN (
    MOV_LAN_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    MOV_SRK INTEGER REFERENCES data_warehouse.FCT_MOV(MOV_SRK),
    LAN_SRK INTEGER REFERENCES data_warehouse.DIM_SPK_LAN(LAN_SRK)
);
