CREATE SCHEMA IF NOT EXISTS warehouse;

CREATE TABLE IF NOT EXISTS warehouse.FCT_MOVIE (
    ID_MOVIE_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CD_MOVIE_NK BIGINT NOT NULL UNIQUE,
    NM_TITLE TEXT NOT NULL,
    DT_RELEASE TIMESTAMP NOT NULL,
    NM_ORIGINAL_TITLE TEXT,
    QT_RUNTIME INT,
    VL_BUDGET BIGINT,
    VL_REVENUE BIGINT,
    VL_POPULARITY REAL,
    VL_VOTE_AVG REAL,
    QT_VOTE_COUNT INT,
    TX_OVERVIEW TEXT,
    TX_TAGLINE TEXT,
    IN_ADULT BOOLEAN,
    VL_STATUS TEXT,
    CD_ORIGINAL_LANGUAGE TEXT
);

CREATE TABLE IF NOT EXISTS warehouse.DIM_GENRE (
    ID_GENRE_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FK_MOVIE INTEGER REFERENCES warehouse.FCT_MOVIE(CD_MOVIE_NK),
    NM_GENRE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS warehouse.DIM_PROD_COMP (
    ID_COMPANY_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FK_MOVIE INTEGER REFERENCES warehouse.FCT_MOVIE(CD_MOVIE_NK),
    NM_PRODUCTION_COMPANY TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS warehouse.DIM_COUNTRY (
    ID_COUNTRY_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FK_MOVIE INTEGER REFERENCES warehouse.FCT_MOVIE(CD_MOVIE_NK),
    NM_PRODUCTION_COUNTRY TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS warehouse.DIM_SPOKEN_LAN (
    ID_LANGUAGE_SRK INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FK_MOVIE INTEGER REFERENCES warehouse.FCT_MOVIE(CD_MOVIE_NK),
    NM_SPOKEN_LANGUAGE TEXT NOT NULL
);
